server:
  port: ${port:8081}
#  servlet:
#    context-path: /api

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    password: ${springDatasourcePassword}
    url: ${springDatasourceUrl}
    username: ${springDatasourceUsername}
  profiles:
#    active: '@active.profile@'
   active: 'local'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
#  graphql:
#    graphiql:
#      enabled: true
  cloud:
    discovery:
      enabled: true
management:
  endpoints:
    web:
      exposure:
       include:
         - '*'