#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081/
#          predicates:
#            - Path= /customers/**
#        - id: r2
#          uri: http://localhost:8082/
#          predicates:
#            - Path= /products/**

#don't do that in prod
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET